server:
    port: ${SERVER_PORT}

spring:
    application:
        name: hystrix-dashboard
    cloud:
        discovery:
            enabled: true

eureka:
    instance:
        leaseRenewalIntervalInSeconds: 10
        health-check-url-path: /actuator/health
        metadata-map:
            startup: ${random.int}    #needed to trigger info and endpoint update after restart
    client:
        registryFetchIntervalSeconds: 5
        serviceUrl:
            defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: "*"
